### ISSUE TITLE
Support blocking on deletion for specific resources

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#101]
It would be great if we can have a whitelist or blacklist mode for resources and make the deletion check block on it.

Examples:
- in mode whitelist deletions of specific types are allowed. If a new resource wants to be deleted and allowed then first send a PR allowing that resource or resource type.
- in mode blacklist deletions of specific types are not allowed. Thus for example you can prevent any deletion of sensitive resources like GKE cluster or PHI holding resources like healthcare stores.

**Comment by MartinPetkov** [comment]
Assigning myself because most likely I'll do it (eventually).

What if blacklists and whitelists overlap? I propose the check just fails and outputs an error, "resource X matched both whitelist and blacklist".

**Comment by umairidris** [comment]
So this needs to be thought about more, but what is the default? If the default is allow deletion then what's the advantage of maintaining your own whitelist? If default is disallow deletion then what's the advantage of blacklists?

So I guess you would only pick one mode depending on how strict you want to be?

**Comment by MartinPetkov** [comment]
I think the default should be **disallow deletion**, and the whitelist overrides that. I can see a blacklist being like a filter after the whitelist. Example, whitelist allows deleting any network, but blacklist prevents one special network from being deleted.

**Comment by umairidris** [comment]
Sounds good. For simplification I think having a single 'mode' field and 'excludes' can be considered.

**Comment by MartinPetkov** [comment]
That's a good idea. I think that's better.
