### ISSUE TITLE
Change Apply triggers behaviour for CICD recipe

### ISSUE THREAD

**Issue by ernestognw** [GoogleCloudPlatform/healthcare-data-protection-suite#1014]
## Description

Prior to #949, triggers were rendered using Go Templating system, which is pretty straightforward, but after the specified PR was completed, some other PRs followed (#1006, #1009) with the objective to migrate the templating logic into a fully HCL dependant, which means controlling everything based on variables provided to the root CICD module.

## Context

The new variable controlled oriented approach introduced extra complexities to the composition of the triggers module, creating a difficult to read and maintain state driven by combination of variables and empty states (things like `skip` + `run_on_schedule` combined together to condition certain resources)

The original behaviour for the triggers is specified by the `v0.9.0` release [here](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/v0.9.0/templates/tfengine/components/cicd/triggers.tf), with the following logic:

### For `validate`, `plan` and `apply`
1. If the validate/plan key is provided with an empty map `{}` for the configuration, then the defaults are set:
1.1 Creates a push trigger (`run_on_push` defaults to true)
1.2 Does not create a scheduled trigger and does not create its scheduler
2. If no validate/plan key is provided (nil), then nothing it's created
3. If the validate/plan key is provided with inner values `{ ... }` then the values are applied with priority over the defaults

### For `validate` and `plan`
1. The push trigger and the scheduled trigger are separated. Both are different resources and don't mix

### For `apply`
1. The scheduled trigger is the same as the push trigger, it responds to `push` event when `github` configuration is provided
2. Since the scheduled trigger is the same, it is enabled when `run_on_push` is provided as `true`

## Problem

After #1009, the current state will depend totally on the `terraform.tfvars` provided, and the simplification of the triggers into a module led to a state where the `triggers` module includes the 3 following resources:

1. A `push` trigger
2. An `scheduled` trigger
3. An scheduler to trigger the `scheduled` trigger

These 3 resources are controlled at one level up to customize and create depending on the `apply`, `validate` and `plan` variables.

The current problem is that, since the beginning, the behaviour for the `apply` trigger was different, meaning that is needed to create a strange combination of variables to reuse the `scheduled` trigger as the `push` one. To solve this issue it is needed to provide a more consistent version of the triggers

## Proposed solution

While the current state should be working fine, it's difficult to read and maintained as previously stated. The proposed solution contemplates the following:

1. Change the behaviour of the `apply` command to create two triggers as well as the `validate` and `plan`
2. These two triggers should be the same that are already created inside the `triggers` module **(no extra one is required)**
3. Separate the responsibility of the `scheduled` trigger to not act as a `push` trigger as well
4. Remove extra control variables needed (much of this variables were added to compose them in order to make the `apply` trigger to work)

## Known difficulties
1. One of the main reasons this wasn't done on the very first try, is because the `apply` push and scheduled trigger uses `push` block when `github` is provided, so that's why the original `push` trigger cannot be used unless more control variables are added. This might be the more difficult challenge while solving this issue
2. Remove variables from the `triggers` module should be theoretically doable to make it more consistent and cleaner. Many of this variables are there just to manipulate the triggers so the `apply` can exists and work correctly. The difficulty will be backtrack which variables were added with the only purpose of making `apply` to work

**Comment by xingao267** [comment]
Note this is for the blueprints branch.

**Comment by xingao267** [comment]
Closing this for now. Will reopen if needed.
