### ISSUE TITLE
CICD job failed on starting developer-tools-light image

### ISSUE THREAD

**Issue by yeweidaniel** [GoogleCloudPlatform/healthcare-data-protection-suite#1043]
After setting up CICD on Oct 18th, upon pushing a Git commit to a `shared` branch, the `tf-apply-shared` job failed on two consecutive tries with the error message:

> HEAD is now at 44adb80 shared
> BUILD
> Starting Step #0 - "Terraform version"
> Step #0 - "Terraform version": Pulling image: gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011
> Step #0 - "Terraform version": gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011: Pulling from cloud-foundation-cicd/cft/developer-tools-light
> Step #0 - "Terraform version": 540db60ca938: Pulling fs layer
> Step #0 - "Terraform version": bcf39eeba39e: Pulling fs layer
> Step #0 - "Terraform version": acacc11c515b: Pulling fs layer
> Step #0 - "Terraform version": fe4c8555656d: Pulling fs layer
> Step #0 - "Terraform version": 06a1781f294f: Pulling fs layer
> Step #0 - "Terraform version": c8e18101236f: Pulling fs layer
> Step #0 - "Terraform version": 5e420a7acffa: Pulling fs layer
> Step #0 - "Terraform version": fe4c8555656d: Waiting
> Step #0 - "Terraform version": 06a1781f294f: Waiting
> Step #0 - "Terraform version": c8e18101236f: Waiting
> Step #0 - "Terraform version": 5e420a7acffa: Waiting
> Step #0 - "Terraform version": 540db60ca938: Verifying Checksum
> Step #0 - "Terraform version": 540db60ca938: Download complete
> Step #0 - "Terraform version": fe4c8555656d: Download complete
> Step #0 - "Terraform version": 540db60ca938: Pull complete
> Step #0 - "Terraform version": bcf39eeba39e: Verifying Checksum
> Step #0 - "Terraform version": bcf39eeba39e: Download complete
> Step #0 - "Terraform version": c8e18101236f: Verifying Checksum
> Step #0 - "Terraform version": c8e18101236f: Download complete
> Step #0 - "Terraform version": 5e420a7acffa: Verifying Checksum
> Step #0 - "Terraform version": 5e420a7acffa: Download complete
> Step #0 - "Terraform version": acacc11c515b: Verifying Checksum
> Step #0 - "Terraform version": acacc11c515b: Download complete
> Step #0 - "Terraform version": 06a1781f294f: Verifying Checksum
> Step #0 - "Terraform version": 06a1781f294f: Download complete
> Step #0 - "Terraform version": bcf39eeba39e: Pull complete
> Step #0 - "Terraform version": acacc11c515b: Pull complete
> Step #0 - "Terraform version": fe4c8555656d: Pull complete
> Step #0 - "Terraform version": 06a1781f294f: Pull complete
> Step #0 - "Terraform version": c8e18101236f: Pull complete
> Step #0 - "Terraform version": 5e420a7acffa: Pull complete
> Step #0 - "Terraform version": Digest: sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011
> Step #0 - "Terraform version": Status: Downloaded newer image for gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011
> Step #0 - "Terraform version": gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011
> Step #0 - "Terraform version": Terraform v0.14.8
> Step #0 - "Terraform version": 
> Step #0 - "Terraform version": Your version of Terraform is out of date! The latest version
> Step #0 - "Terraform version": is 1.0.9. You can update by downloading from https://www.terraform.io/downloads.html
> Finished Step #0 - "Terraform version"
> Starting Step #1 - "Import existing projects"
> Step #1 - "Import existing projects": Already have image (with digest): gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011
> Finished Step #1 - "Import existing projects"
> ERROR
> ERROR: build step 1 "gcr.io/cloud-foundation-cicd/cft/developer-tools-light@sha256:d881ce4ff2a73fa0877dd357af798a431a601b2ccfe5a140837bcb883cd3f011" failed: step exited with non-zero status: 8

Retrying the following day (Oct 19) succeeded without any changes. The Cloud Build log did not provide additional details on the error.

**Comment by xingao267** [comment]
@yeweidaniel does this issue still happen?

**Comment by xingao267** [comment]
I'll close for now. Pls reopen if it happens again.
