### ISSUE TITLE
Add some cron job to periodically run `terraform plan` to detect unexpected changes/upgrades.

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#105]

**Comment by umairidris** [comment]
Doesnt https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/100 remove the need for this? Or this to make users aware that next time they make a change in that deployment there maybe unrelated changes along with it?

**Comment by xingao267** [comment]
Yes. It's for unrelated or unexpected changes, maybe introduced by a manual change on GCP or unexpected module ungrades.
