### ISSUE TITLE
module.bigquery_destination.google_bigquery_dataset.main has change but not applied all the time

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#12]
Example:

Terraform will perform the following actions:

  # module.bigquery_destination.google_bigquery_dataset.main will be updated in-place
  ~ resource "google_bigquery_dataset" "main" {
        creation_time                   = 1586210668516
        dataset_id                      = "1yr_org_audit_logs"
        default_partition_expiration_ms = 0
        default_table_expiration_ms     = 31536000000
        delete_contents_on_destroy      = false
        etag                            = "xsgr8/dA8yPpPQ8cHO4lZQ=="
        id                              = "projects/<project_id>datasets/1yr_org_audit_logs"
        labels                          = {}
        last_modified_time              = 1588147206214
        location                        = "us-east1"
        project                         = "<project_id>"
        self_link                       = "https://www.googleapis.com/bigquery/v2/projects/<project_id>/datasets/1yr_org_audit_logs"

      - access {
          - role          = "OWNER" -> null
          - special_group = "projectOwners" -> null
        }
      + access {
          + role          = "roles/bigquery.dataOwner"
          + special_group = "projectOwners"
        }
      - access {
          - group_by_email = "rocketturtle-gcp-admin@rocketturtle.net" -> null
          - role           = "READER" -> null
        }
      + access {
          + group_by_email = "rocketturtle-gcp-admin@rocketturtle.net"
          + role           = "roles/bigquery.dataViewer"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by umairidris** [comment]
Fixed: https://github.com/terraform-google-modules/terraform-google-bigquery/releases/tag/v4.1.0
