### ISSUE TITLE
Support filtering plans so the log is more readable.

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#15]

**Comment by umairidris** [comment]
IMO #14 actually removes the need for this. If we only apply the changing parts then the plans should be much smaller and more readable. And it can be useful to see if you make a change but the plan shows no diff. I would focus on this I think it will be a huge improvement in avoiding applying the entire infra every PR.

**Comment by xingao267** [comment]
I'll do a little improvement on the terragrunt part. Only apply changing parts and move some of the dependency logic to cloud build config is more involving and I need think about that a little more.
