### ISSUE TITLE
Format and check hcl example/recipes

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#175]
Currently only terraform .tf and terragrunt.hcl files are checked.

**Comment by umairidris** [comment]
On the other hand, since examples and recipes have templates, this may not be possible...

**Comment by MartinPetkov** [comment]
We can at least format and check the generated files.

**Comment by umairidris** [comment]
Yeah, filed https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/356 for that. I think for this issue we will just stick to checking the examples.

**Comment by xingao267** [comment]
This is done right?

**Comment by umairidris** [comment]
I don't think we're checking format on examples yet

**Comment by xingao267** [comment]
obsolete, won't fix
