### ISSUE TITLE
guidance on timeline?

### ISSUE THREAD

**Issue by starcrest** [GoogleCloudPlatform/healthcare-data-protection-suite#311]
Sorry to bother, but I'm spinning up a new project and wondering whether to use this codebase or the older toolkit [here](https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/README.md#create-new-projects). I'm assuming the older version is more fully-featured and well-documented, while you actively develop here. 

Any guidance on when this codebase will be ready for active usage, and when it will be initially "released"?

**Comment by umairidris** [comment]
Hi @starcrest,

Thanks for your interest! Without knowing your exact use case it is hard to give a definitive answer, but as a general rule of thumb I would recommend using the new toolkit over the older version. The main reason is our new approach: in the old toolkit the toolkit config is the primary source of truth for your infra and changes are recommended to be made in that config.

The new toolkit takes a different approach. The output is Terraform configs which you manage and deploy yourself (the toolkit is no longer needed beyond that step). The configs we generate use production ready cloud foundation toolkit modules for the most part (https://cloud.google.com/foundation-toolkit) and thus are generaly reliable.

We don't have definitive timelines at the moment but we hope to continue stabilizing things over the next month or two. Most things are in place and we're actively working on simplification and documentation now. You can expect an alpha launch coming in the next few weeks.

A good starting point is the examples dir: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/tree/master/examples/tfengine which has a simple and complex use case. We look forward to hearing feedback and pain points you encouter in the future.

**Comment by umairidris** [comment]
I am going to consider this issue resolved. If you have anymore questions/concerns please open new issues. Thanks!
