### ISSUE TITLE
Feature parity with DPT

### ISSUE THREAD

**Issue by gbhojak** [GoogleCloudPlatform/healthcare-data-protection-suite#328]
Hi,

I would like to understand how does this new suite compare with existing DPT solution [here](https://github.com/GoogleCloudPlatform/healthcare).

I have been reading [this guide ](https://cloud.google.com/solutions/architecture-hipaa-aligned-project) and [this one as well](https://cloud.google.com/solutions/setting-up-a-hipaa-aligned-project) to setup our infrastructure for HIPPA.
We are trying to build an infrastructure that closely resembles [this](https://cloud.google.com/solutions/architecture-hipaa-aligned-project#architecture_diagram).

Looking at the full.hcl example, it does look like that with this approach each of our environments such as staging and production would have their own devops/audit/monitoring GCP projects. Is this the right assumption?
Also, would it make to have multiple copies of full.hcl and create one for each env, like full-staging and full-prod or something like that?

I am really excited to try this out for our needs. Just need to understand above differences.
Apologies for asking so many questions in one go. Just getting started with this suite and in the process of creating staging and production envs.

Regards,
Giriraj

**Comment by umairidris** [comment]
Hi Giriraj,

Thanks for your interest! In terms of features, I would say the new toolkit is relatively on par with DPT. It in fact supports more features such as org level auditing/monitoring and networking resources natively. Where things are lacking are documentations and clearer examples which we are actively working on. 

We will soon be adding some features to support folder level management for things like devops, etc (https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/40).

With the above we will be updating the examples and documentation to better architect organizations.

In general we will recommend:
- one "org" config per org for managing org level auditing and monitoring
- one "folder" config per team/environment

Each of the above will have its own devops project and CICD pipeline.

The folder boundary will depend on each org. For smaller orgs, having a "prod" folder (and thus prod devops) will be fine. So they would have the config files like org_foundation.hcl, folder_prod.hcl, folder_dev.hcl. If it should be for each team/app then you may have something like org_foundation.hcl, folder_prod_team1.hcl, folder_dev_team1.hcl, etc...

We will update the README and examples to reflect the above changes.

I will be sure to include relevant PRs to this issue so you can track them and give feedback.

**Comment by umairidris** [comment]
One thing to keep in mind is you may experience more breaking changes in the next couple of months as we figure out the best way to deploy these complex infra. Thus whenever you sync to head please reference the latest examples to make sure you are not deviating from them.

**Comment by gbhojak** [comment]
@umairidris , thank you for this detailed explanation. That helps a lot.

After creating these projects, I need to deploy additional resources(pubsub, cloud run, firestore indexes, cloud build triggers etc.) in the app project created by project_apps template.
I created a folder structure as recommended by Terragrunt for **qa** env.
For subsequent invocations of `terragrunt apply`, does it make sense to use a service account that was created in the apps project?
This is what I just tried: I created a new service account in the devops project and added bunch of roles to it. I gave that service account an IAM role in the apps project.
I did this so that the service account would have access to the remote state bucket.
Does this approach make sense?

Also, would it be possible to use the template for  "`project_firebase`" in a way that I can treat firebase project as the only apps project. Our app uses a single GCP project to manage firebase and other compute requirements(cloud run, pub/sub etc.)

Other things I have stumbled upon:

- cscc_source_id in monitor project -- where to get this id?

- What should be the customer id in the org policies?

    org policies where to get customer id
        allowed_policy_member_customer_ids = [
      "example_customer_id",
     ]

- Is it possible to enable additional APIs for devops project?

Also, if it helps for documentation -- I had to add the '**Compute Shared VPC Admin**' role to the user at the org level so that the shared VPC project could be used.

**Comment by gbhojak** [comment]
I also stumbled with following two errors for the monitor project -- I am not running the deployment under live folder using a different service account, it's my own user credentials that are set via `gcloud auth login`.
I have following roles on my account at the org level:

- Owner
- Folder Admin
- Folder Editor
- Organization Administrator

`module.project.module.project-factory.null_resource.preconditions (local-exec): Executing: ["/bin/sh" "-c" "python3 /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/monitor/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py --billing_account=\"<billing_account>\" --credentials_path=\"\" --folder_id=\"\" --impersonate_service_account=\"\" --org_id=\"<org_id>\" --shared_vpc=\"\" "]
google_folder.folder: Still creating... [10s elapsed]
module.project.module.project-factory.null_resource.preconditions (local-exec): /Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
module.project.module.project-factory.null_resource.preconditions (local-exec):   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
module.project.module.project-factory.null_resource.preconditions (local-exec): WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
module.project.module.project-factory.null_resource.preconditions (local-exec): Traceback (most recent call last):
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/monitor/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 492, in <module>
module.project.module.project-factory.null_resource.preconditions (local-exec):     retcode = main(sys.argv)
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/monitor/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 474, in main
module.project.module.project-factory.null_resource.preconditions (local-exec):     results.append(validator.validate(credentials))
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/monitor/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 262, in validate
module.project.module.project-factory.null_resource.preconditions (local-exec):     response = request.execute()
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
module.project.module.project-factory.null_resource.preconditions (local-exec):     return wrapped(*args, **kwargs)
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
module.project.module.project-factory.null_resource.preconditions (local-exec):     raise HttpError(resp, content, uri=self.uri)
module.project.module.project-factory.null_resource.preconditions (local-exec): googleapiclient.errors.HttpError: <HttpError 403 when requesting https://serviceusage.googleapis.com/v1/projects/<project_id>-apps/services/admin.googleapis.com?alt=json returned "The caller does not have permission">
module.project.module.project-factory.null_resource.preconditions (local-exec): /Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
module.project.module.project-factory.null_resource.preconditions (local-exec):   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
module.project.module.project-factory.null_resource.preconditions (local-exec): WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
`


And
 
     module.forseti.google_project_service.main[16]: Refreshing state... [id=<project_id>
       monitor/spanner.googleapis.com]

     : googleapi: Error 409: Sink bigquery-org-sink already exists, alreadyExists

    on .terraform/modules/bigquery_log_export/terraform-google-log-export-4.0.1/main.tf line 58, in resource " 
     google_logging_organization_sink" "sink":
     58: resource "google_logging_organization_sink" "sink" {



     Error: googleapi: Error 409: Sorry, that name is not available. Please try a different one., conflict

     on .terraform/modules/storage_destination/terraform-google-cloud-storage-1.6.0/modules/simple_bucket/main.tf line 17, 
     in resource "google_storage_bucket" "bucket":
     17: resource "google_storage_bucket" "bucket" {


     [terragrunt] [/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/audit/resources] 
     2020/06/23 23:05:15 Module /Users/giriraj/source/2020/healthcare/healthcare-data-protection- 
    suite/output/live/audit/resources has finished with an error: Hit multiple errors:
     exit status 1
`


And a similar error for apps project:

`module.project.module.project-factory.null_resource.preconditions: Provisioning with 'local-exec'...
module.project.module.project-factory.null_resource.preconditions (local-exec): Executing: ["/bin/sh" "-c" "python3 /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/prod/app-team/<project_id>-apps/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py --billing_account=\"<billing_id>\" --credentials_path=\"\" --folder_id=\"folders/<folder_id>\" --impersonate_service_account=\"\" --org_id=\"<org_id>\" --shared_vpc=\"<project_id>\" "]
module.project.module.project-factory.null_resource.preconditions (local-exec): /Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
module.project.module.project-factory.null_resource.preconditions (local-exec):   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
module.project.module.project-factory.null_resource.preconditions (local-exec): WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
module.project.module.project-factory.null_resource.preconditions (local-exec): Traceback (most recent call last):
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/prod/app-team/<project_id>/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 492, in <module>
module.project.module.project-factory.null_resource.preconditions (local-exec):     retcode = main(sys.argv)
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/output/live/prod/app-team/<project_id>/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 474, in main
module.project.module.project-factory.null_resource.preconditions (local-exec):     results.append(validator.validate(credentials))
`

**Comment by umairidris** [comment]
> @umairidris , thank you for this detailed explanation. That helps a lot.
> 
> After creating these projects, I need to deploy additional resources(pubsub, cloud run, firestore indexes, cloud build triggers etc.) in the app project created by project_apps template.
> I created a folder structure as recommended by Terragrunt for **qa** env.
> For subsequent invocations of `terragrunt apply`, does it make sense to use a service account that was created in the apps project?
> This is what I just tried: I created a new service account in the devops project and added bunch of roles to it. I gave that service account an IAM role in the apps project.
> I did this so that the service account would have access to the remote state bucket.
> Does this approach make sense?
> 
> Also, would it be possible to use the template for "`project_firebase`" in a way that I can treat firebase project as the only apps project. Our app uses a single GCP project to manage firebase and other compute requirements(cloud run, pub/sub etc.)
> 
> Other things I have stumbled upon:
> 
> * cscc_source_id in monitor project -- where to get this id?
> * What should be the customer id in the org policies?
>   org policies where to get customer id
>   allowed_policy_member_customer_ids = [
>   "example_customer_id",
>   ]
> * Is it possible to enable additional APIs for devops project?
> 
> Also, if it helps for documentation -- I had to add the '**Compute Shared VPC Admin**' role to the user at the org level so that the shared VPC project could be used.

You can find details of the fields in the respective recipe e.g. https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/recipes/monitor.hcl#L42. They will also have documentation on how to get the fields if it is not obvious.

@xingao267 should we consider renaming cscc_source_id to "security_command_centre_id" so that it's more obvious?

It is currently not possible to enable APIs in the devops project unless you go through the CICD pipeline. I think it's a reasonable request and filed https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/346 to follow up on it. In the meantime if you're not using CICD you can modify the generated files manually (beware they will get overwritten if you run the engine again).

We recommend deploying things using the cloud build based CICD process. When you use that the CICD service account is given the necessary permissions to deploy everything in the org/folder. Also, if you use the CICD to create the projects it will automatically get owner access to the project. You should not need to manually deploy projects then create additional service accounts and manually grant those permissions.

I will soon be replacing full.hcl with prod_team1.hcl which you can follow to setup a devops/CICD at both an org and then the folder level.

For troubleshooting individual resources/modules please file bugs in the respective [cloud foundation toolkit](https://github.com/terraform-google-modules) module repo or the [terraform provider](https://github.com/terraform-providers/terraform-provider-google).

**Comment by xingao267** [comment]
Sent https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/347 to improve the doc around how to use cscc with Forseti.

**Comment by gbhojak** [comment]
> We recommend deploying things using the cloud build based CICD process. When you use that the CICD service account is given the necessary permissions to deploy everything in the org/folder. Also, if you use the CICD to create the projects it will automatically get owner access to the project. You should not need to manually deploy projects then create additional service accounts and manually grant those permissions.

Thank you @umairidris , I did not use the CICD block at all in full.hcl, since I am still trying this toolkit out and trying to deploy infrastructure by running scripts manually. Does this mean even if I need to deploy GKE clusters, VMs etc in the **apps** project, I need to use the **devops** Cloud Build account?

I think I am still not clear on how the CICD process for deploying this toolkit would work alongside the additional GCP resources that needs to be added. I will go through the CICD documentation in the components directory. 

I will enable the APIs by modifying the generated config for  devops project now. Thank you for that trick.

**Comment by gbhojak** [comment]
HI @umairidris , I am trying the examples for folder_foundation.hcl and team.hcl.
Does the team need to share the same devops project as the folder?
I ran the folder_foundation example and then used the same devops project for team.hcl and it failed saying '`Error 409: Requested entity already exists`'.

**Comment by umairidris** [comment]
Hi Giriraj,

If you want a single devops to manage everything within a single folder then you can just copy all the content from folder_foundation.hcl into team.hcl except the devops template (don't duplicate it).

If you want to mimic what you would do for an org then youc an have a 'root' folder which has foundation and can create other sub folders. You can then pass the id of one of the sub folders to team.hcl and have it deployed within that folder.

**Comment by gbhojak** [comment]
Hi @umairidris , 

Do you mean to say I should copy the monitor and audit templates from folder_foundation.hcl into team.hcl as well ?
What I was thinking based on your response is that I will keep the devops, audit and monitoring templates in folder_foundation.hcl and just remove devops template from team.hcl.

**Comment by umairidris** [comment]
Both will work but ideally you should only have one config file per devops/CICD. The reason is with a single terragrunt apply-all command the CICD can deploy everything it manages. If you split it across multiple config files you need to make sure you output them all to the same directory.

**Comment by gbhojak** [comment]
Thank you for that clarification, I actually do need to keep everything under one folder for now. I will simply add auditing and monitoring templates to the team.hcl and try it out. Thank you Umair.

**Comment by gbhojak** [comment]
Hi @umairidris, With devops/audit/monitoring in a single file, I was able to run terraform on bootstrap and cicd without any issue.
But running `terragrunt apply-all` under live folder throws following errors:

    Error: Error setting billing account "<billing account id>" for project "projects/lo-temp43-monitor": googleapi: Error 400: 
    Precondition check failed., failedPrecondition

and
```
module.project.module.project-factory.null_resource.preconditions (local-exec): Executing: ["/bin/sh" "-c" "python3 /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-apps/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py --billing_account=\"<billing_id>\" --credentials_path=\"\" --folder_id=\"<folder-id>\" --impersonate_service_account=\"\" --org_id=\"\" --shared_vpc=\"lo--temp43-prod-networks\" "]
module.project.module.project-factory.null_resource.preconditions (local-exec): /Users/giriraj/source/2020/healthcare/venv/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
module.project.module.project-factory.null_resource.preconditions (local-exec):   warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
module.project.module.project-factory.null_resource.preconditions (local-exec): Traceback (most recent call last):
module.project.module.project-factory.null_resource.preconditions (local-exec):   File "/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-apps/project/.terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/scripts/preconditions/preconditions.py", line 492, in <module>
```
and 
```
Error: Error enabling the Compute Engine API required to delete the default network: Error waiting for Enable Project "lo-temp43-prod-apps" Services: [compute.googleapis.com]: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 4m0s) 

  on .terraform/modules/project/terraform-google-project-factory-8.0.1/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {
```

Here is the final error output:

```
[terragrunt] 2020/06/25 19:54:44 Encountered the following errors:
Cannot process module Module /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/monitor/forseti (excluded: false, dependencies: [/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/monitor/project]) because one of its dependencies, Module /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/monitor/project (excluded: false, dependencies: []), finished with an error: Hit multiple errors:
exit status 1
Hit multiple errors:
exit status 1
Hit multiple errors:
exit status 1
Cannot process module Module /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-apps/resources (excluded: false, dependencies: [/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-apps/project]) because one of its dependencies, Module /Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-apps/project (excluded: false, dependencies: [/Users/giriraj/source/2020/healthcare/healthcare-data-protection-suite/qa-output-apps/live/lo-temp43-prod-networks/resources]), finished with an error: Hit multiple errors:
exit status 1
```

I can see that all the 5 projects were created in the correct folder.
I will investigate them, but hoping you would have a fix for them.

**Comment by umairidris** [comment]
Are you able to manually create a project and attach it to that billing account? Billing accounts have a max number of projects that can be attached so you might be hitting that.

**Comment by gbhojak** [comment]
Thanks @umairidris , that was it. As part of trying out the toolkit, I had created a lot of projects. But I have deleted almost all of them.
I guess those deleted projects are still attached to the billing account.

**Comment by gbhojak** [comment]
Hi @umairidris, I have moved past that error after deleting some of the dormant projects. Thank you for pointing that out.
In order to run the scripts manually to quickly test the changes, can I use any service account created by tfconfig?
Instead of using CICD while testing, if there is way I can use a key via `GOOGLE_APPLICATION_CREDENTIALS` locally, then I can quickly create a QA env.

**Comment by umairidris** [comment]
@xingao267 can you advise?

**Comment by xingao267** [comment]
@gbhojak you can use examples like this https://www.terraform.io/docs/providers/google/d/datasource_google_service_account_key.html to create a service account and download the service account key, then set that key in your terraform provider block https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials. Or you can use `GOOGLE_APPLICATION_CREDENTIALS ` env var to point to your downloaded json key https://cloud.google.com/docs/authentication/getting-started, which should be picked up by Terraform by default.

**Comment by xingao267** [comment]
The service account used in CICD is a cloud build internal service account, which doesn't allow you to download a key for that. So you need to create a separate SA and grant the same permission as what we granted to the CICD SA to it.

**Comment by xingao267** [comment]
You can reuse most of the stuff in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/generated/devops/cicd/main.tf#L80, and replace that SA with the service account you created. So those tf configs can grant you SA the same permission as it granted the CICD SA.

**Comment by gbhojak** [comment]
Thank you @xingao267 , that helps a lot.

**Comment by umairidris** [comment]
I am going to consider this issue resolved. Please file additional ones if you encounter any more. Thanks!
