### ISSUE TITLE
Unable to create a nested folder for prod

### ISSUE THREAD

**Issue by gbhojak** [GoogleCloudPlatform/healthcare-data-protection-suite#329]
Hi,

I am trying to create an environment by following full.hcl example.
I need to create the prod folder under an existing folder structure, so I added `parent_type` and `parent_id` to prod folder data element as follows. I would like to ensure that all subsequents services project for data/app/firebase are created under **prod/app-team**

      # Top level prod folder.
      template "folder_prod" {
        recipe_path = "{{$recipes}}/folder.hcl"
        output_path = "./live"
        data = {
          display_name = "prod"
          parent_type = "folder"
          parent_id = "2323121212"
        }
      }
      
      
      # Prod folder for team 1.
      template "folder_team1" {
        recipe_path = "{{$recipes}}/folder.hcl"
        output_path = "./live/prod"
        data = {
          parent_type  = "folder"
          display_name = "app-team"
        }
      }

Using above config gives me following error:

`Error processing module at '/Users/source/healthcare-data-protection-suite/output/live/folder/terragrunt.hcl'. How this module was found: dependency of module at ''/Users/source/healthcare-data-protection-suite/output/live/prod/folder'. Underlying error: Error reading file at path '/Users/source/healthcare-data-protection-suite/output/live/folder/terragrunt.hcl: open '/Users/source/healthcare-data-protection-suite/output/live/folder/terragrunt.hcl: no such file or directory`

Regards,
Giriraj

**Comment by umairidris** [comment]
Thanks for pointing this out. We were already working in a fix which will be launched in #330. Please set 'add_parent_folder_dependency' in `template "folder_prod` once you sync to head.

**Comment by gbhojak** [comment]
Great, thank you. Looking forward to this feature!

**Comment by umairidris** [comment]
FYI after https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/pull/339 you will need to update your folder_prod and folder_team1 output paths to match the new example in the PR.

**Comment by gbhojak** [comment]
Thank you for the update, I will try this out in next few minutes.

**Comment by umairidris** [comment]
You will need to wait for #338 and #339 or checkout those branches.

**Comment by gbhojak** [comment]
Just realized that it's not merged yet!
Will wait for it.

**Comment by umairidris** [comment]
Pleast take a look at the latest examples for usage steps. Also, a change from above is if you have multiple levels of folders then you will need to add `add_parent_folder_dependency = true` to all the child folders.
