### ISSUE TITLE
Format generated files

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#356]

**Comment by xingao267** [comment]
#364

**Comment by xingao267** [comment]
Is this one done?

**Comment by umairidris** [comment]
I still need to port over terraform-clean-syntax so that we convert "${foo}" to just foo.

**Comment by xingao267** [comment]
got it

**Comment by umairidris** [comment]
Re-opening as we still need to clean up empty lines

**Comment by xingao267** [comment]
@umairidris can we also clean up empty lines before 0.2.0 release?

**Comment by umairidris** [comment]
Sure I'll spend some time today looking into this.
