### ISSUE TITLE
missing org_foundation.yaml in repo

### ISSUE THREAD

**Issue by shekharshamra** [GoogleCloudPlatform/healthcare-data-protection-suite#374]
Hi Team,

I am getting this error when running "tfengine --config_path=$CONFIG_PATH --output_path=$OUTPUT_PATH" command.

open examples/tfengine/org_foundation.yaml: no such file or directory

I believe that org_foundation.yaml is missing in this path "examples/tfengine/org_foundation.yaml". Could you please add it or we need to create it at our own.

**Comment by MartinPetkov** [comment]
This appears to be an issue with the README.md. The file is now named `examples/tfengine/org_foundation.hcl`. I'll send a PR to fix it.
