### ISSUE TITLE
Support VPC Service Controls

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#430]

**Comment by careb2b** [comment]
Are you planning to add VPC in examples?

**Comment by umairidris** [comment]
Do you mean vpc networks? There is an example for them here: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/7f23c258dc74660d5ac5d81ea21e2a83c751c586/examples/tfengine/team.hcl#L115

**Comment by careb2b** [comment]
Ok.  Thanks.  I will check it out.

**Comment by xingao267** [comment]
won't fix at this moment, if needed, will reopen

**Comment by xingao267** [comment]
@jordan83 FYI, if you want to upstream some of your work done for VPSSC, feel free to contribute.
