### ISSUE TITLE
Add shell check to presubmit

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#460]

**Comment by xingao267** [comment]
@umairidris is this done?

**Comment by umairidris** [comment]
No, I didn't get around to it. We don't really use shell scrips so if you just wanna close it feel free to do so

**Comment by xingao267** [comment]
The specific check is to run https://github.com/koalaman/shellcheck on our shell scripts under the scripts/ folder and/or any generated shell scripts (e.g. run.sh).

**Comment by xingao267** [comment]
Close for now. If needed in the future, will reopen.
