### ISSUE TITLE
Detect unmanaged files in output dir

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#462]
The output dir could be non-empty, or have old generated files that were not cleaned up. Make that visible to the user.

**Comment by MartinPetkov** [comment]
This should be controllable by flag.

**Comment by umairidris** [comment]
I was thinking this would just be output (not an exit status non zero). Did you have something else in mind?

**Comment by MartinPetkov** [comment]
That would be fine. I would like this: by default it just warns that you generated files in a non-empty directory, and if you set a flag, it would delete files in output directories before writing out the new ones.

**Comment by xingao267** [comment]
Wanted by solutions team to have an optional flag to clean up the output_dir. Default to false to not break current behavior.

**Comment by xingao267** [comment]
@MartinPetkov is it something you have bandwidth to take on? An optional flag to clean up the output dir is sufficient for now. Default to false. A special case is devops, which we don't want to cleanup as it might contain local state during initial deployment when state has not been backed up yet.

**Comment by umairidris** [comment]
Deleting files can lead to some unexpected behaviour, I would suggest just outputting a list of extra files/dirs. The user should be able to take the list and just pass it to rm if they want I imagine...

**Comment by MartinPetkov** [comment]
Yes, I think this is something I can take on. I'll assign myself and start looking.

**Comment by xingao267** [comment]
or it could be a enum flag for different mode

**Comment by xingao267** [comment]
cc @jordan83

**Comment by xingao267** [comment]
> Deleting files can lead to some unexpected behaviour, I would suggest just outputting a list of extra files/dirs. The user should be able to take the list and just pass it to rm if they want I imagine...

what about always listing out existing files/dirs, but have a mode to force delete?

**Comment by umairidris** [comment]
Sure, I just want to avoid the case where user is used to setting a delete flag and then there is a typo/missed dir and they nuke their home dir or something :)

**Comment by xingao267** [comment]
Yea, good point. Probably just outputting a list of extra files/dirs is enough to serve the purpose and avoid potential disastrous behavior.
