### ISSUE TITLE
Implement a hasOne function in funcmap.go

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#485]
It is useful, for example, to check one of github{} and cloud_source_repository{} block exists or one of "validate" "plan" "apply" exist in .cicd.triggers block.

**Comment by umairidris** [comment]
I don't think you even need all the has checks. I think you can just make

`and (has . "cicd") (or (has .cicd.triggers "validate") (has .cicd.triggers "plan") (has .cicd.triggers "apply")`

`has . "cicd.triggers"

**Comment by xingao267** [comment]
`triggers` is currently set required in `cicd`. So technically you can have an empty `triggers{}` block.

I agree with leaving this check to the json schema checks if they have something like for this.

**Comment by umairidris** [comment]
I would say this is no longer needed. CICD is its own template now that doesn't have the original line in question.
