### ISSUE TITLE
Make --input_dir optional

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#52]
We should allow users to run the importer and by default it should try to run in the cwd.

**Comment by MartinPetkov** [comment]
I think this is already the case. The default value is `.`: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/edd5dc8/cmd/tfimport/main.go#L39

**Comment by umairidris** [comment]
Can we update the documentation to showcase this example? I think this is the more common approach for terraform cenetered tools like terragrunt.
