### ISSUE TITLE
Shared audit and monitoring projects across subfolders

### ISSUE THREAD

**Issue by gbhojak** [GoogleCloudPlatform/healthcare-data-protection-suite#556]
Hi,

Is it possible to have a single audit project and a single monitor project that can audit and monitor resources in the current folder and also all the resources in all the projects of the sub folders as well? We are trying to centralize the auditing and monitoring requirements for all our products that are (or will be pretty soon) in production.
This is the folder hierarchy I am trying to achieve:

* production-folder
  * shared-monitor-proj
  * shared-audit-proj
  * productA-folder
     * productA-apps-proj
     * productA-networks-proj
     * productA-devops-proj
  * productB-folder
     * productB-apps-proj
     * producttB-networks-proj
     * productB-devops-proj

If we can use the same monitor and audit projects from the production folder to take care of our products from sub folders as well, then we can avoid creating those specific  projects for each of the sub folders and hopefully save some costs of running multiple monitoring projects where each project has it's own Cloud SQL instance.

Could you please let me know if it's possible to achieve above hierarchy with the suite?

Thanks,
Giriraj

**Comment by umairidris** [comment]
Slightly different.

1. Create the folders `production-folder`, `shared-proj-monitoring`, etc.
2. Edit folder_foundation to create the audit and monitor deployments within the shared folders.
3. Change `google_logging_folder.folder` to point to `production-folder` instead of the default shared folder for audit
4. Change composite_root_resources in Forseti monitoring to point to `production-folder`.

**Comment by umairidris** [comment]
We can also modify the audit and monitor templates to accept an override for those individual fields. I can guide you on how to make the contribution, otherwise feel free to continue with manual modifications.

**Comment by xingao267** [comment]
@gbhojak does https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/multi_envs.hcl help with this issue?

**Comment by xingao267** [comment]
Shared audit and monitoring projects across subfolders is supported and demonstrated in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/multi_envs.hcl
