### ISSUE TITLE
Add a typical GKE application template

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#621]
A standard simple GKE application template which has the following projects:

- devops
- audit
- networks (one VPC and one subnet with a NAT)
- apps (a SA and a Cluster)
- kubernetes (placeholder k8s deployment yaml)

**Comment by umairidris** [comment]
Isn't that the teams example? Or do you mean a dedicated template for it?

**Comment by xingao267** [comment]
I was thinking of a more dedicated template for a simple GKE app with a shared VPC including a place holder k8s yaml config. team.hcl contains other stuff which seems over complicated for this use case and might cause some distraction?

**Comment by umairidris** [comment]
Yeah I think that makes sense. A starter recipe that people can fork/use as starting point and make changes to their needs can be good.
