### ISSUE TITLE
Doubt on architecture structure with org_foundation.hcl

### ISSUE THREAD

**Issue by sumeshsquare** [GoogleCloudPlatform/healthcare-data-protection-suite#644]
Hi Team,

By following the org_foundation.hcl example, I came with an arch-like below.
![image](https://user-images.githubusercontent.com/36350499/99364034-7c1a9d80-28db-11eb-965e-b51337849ce0.png)

From the above diagram, my doubt is, does the Project - Devops, Audit, Network, and Monitor should come directly under Org without Folder?
Also for newer tenants, I have split the DEV and PROD with Folder for isolation and adding the CICD recipe into the new Projects.

Any suggestions, Does this looks good? please assist.

Thanks!

**Comment by umairidris** [comment]
Hi @sumeshsquare,

This seems similar to https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/556. We are working on moving the folders away from org to a shared folder. It is currently only supported in the upcoming app example: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/app.hcl.

We will eventually migrate other examples to follow this pattern in the future.

**Comment by sumeshsquare** [comment]
Hi @umairidris, Thanks for the reply, I went through the case which you mentioned. 

Updated Architecture below, please suggest.

![gcp_dec1-1](https://user-images.githubusercontent.com/36350499/100730677-5cfa3080-33f0-11eb-95d5-7ebf57f03c63.jpg)

**Comment by xingao267** [comment]
@sumeshsquare the CICD should go under Devops. Other than that, it look good to me. Whether or not putting shared projects under its own folder or directly under Org are both fine to me.
