### ISSUE TITLE
Extend CICD to support GKE app deployment

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#658]

**Comment by xingao267** [comment]
Verify kubernetes_* resources can be successfully deployed and fix any issues occurred.

**Comment by xingao267** [comment]
Container service agent needs permission in the host network project to create additional firewall rules for health check. Upstream PR sent for review https://github.com/terraform-google-modules/terraform-google-project-factory/pull/536

**Comment by umairidris** [comment]
I thought the regular project factory module can now also create vpc attachments, so why do we still need to use the shared vpc module? It seems to always get out of sync.

**Comment by xingao267** [comment]
@umairidris I think that's separate issue tracked in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/697. Neither the PF main module nor the service project module supports that field at this moment.

**Comment by umairidris** [comment]
Ah right, thanks for clarifying. We should look into fixing that for the next major release (might cause some existing projects to become recreated tho).

**Comment by xingao267** [comment]
Another issue in the module: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/789
