### ISSUE TITLE
Improve CICD to automatically crawl over generated Terraform config directories and deploy configs

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#696]
instead of explicitly listed out all directories in the `managed_dirs` attribute in the cicd template.

**Comment by umairidris** [comment]
This already happens in the app foundation. But we should have an option to skip directories as well if they can't be deployed by automation e.g. kubernetes

**Comment by xingao267** [comment]
App foundation relies on a fixed directory structure and hasn't been integrated with existing CICD yet. I was thinking having something that can understand the generated directories, find TF files and figure out a deployment order and list by itself. It's likely not easy. But yes, first step we can do is trying to simplify the `managed_dirs` list and build in more assumption as what app foundation do. And being able to skip dirs in CICD is definitely a nice feature to have.
