### ISSUE TITLE
The version of the latest binary should show a date of built instead of just latest

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#700]

**Comment by MartinPetkov** [comment]
Do you mean the binary's name, or the actual version when checking the version in the Go code?

**Comment by xingao267** [comment]
the actual version that gets printed out when you run `tfengine --version`

**Comment by MartinPetkov** [comment]
I see. Just wondering, wouldn't that be an issue because you wouldn't be able to pin to just "latest"?

**Comment by xingao267** [comment]
I can download the latest binary every time I use it. But if my local `tfengine` binary can show a version like `latest as 2020-11-01`, it's a better than showing `latest` which it's no longer the real latest.
