### ISSUE TITLE
Support for GKE + ConfigSync + ConfigConector + Application Delivery

### ISSUE THREAD

**Issue by josemolmomillan** [GoogleCloudPlatform/healthcare-data-protection-suite#705]
Hello

    We are thinking of developing our Infrastructure as Code and GitOps model based on 
GKE + ConfigSync + ConfigConnector + ApplicationDelivery, that is, mainly yaml and gitops repos 
for gke, gcp resources and app deployments.

   The only thing that does not cover that approach is:
- initial GKE bootstrap
- forseti policies / audit on GKE

Do you have plans to support GKE, forseti on GKE and definition of resources / apps in GKE in this project?

Cheers

**Comment by umairidris** [comment]
Hi @josemolmomillan,

Thanks for your question and apologies for the delayed response. You can look at our example in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/team.hcl for how to set up a GKE cluster through automation. Note that kubernetes resources deployed through the kubernetes provider does not work through Cloud Build, so will need to be applied separately.

We don't have plans on supporting forseti on GKE as that effort does not seem to be mature at this point. You can however find other examples of k8s resources in the team example above.
