### ISSUE TITLE
managed_dirs in cicd seems broken

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#735]
It's set in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/team.hcl#L160

But not in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/generated/team/cicd/configs/run.sh#L20

**Comment by xingao267** [comment]
The values are passed to https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/generated/team/cicd/triggers.tf#L69 and then to the run.sh script via a flag https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/generated/team/cicd/configs/tf-plan.yaml#L31

**Comment by umairidris** [comment]
Ah I see. What is the motivation behind the change? It prevents people from directly running run.sh locally

**Comment by xingao267** [comment]
The change was introduced in the multi env support PR #645. This way, we don't need to duplicate `run.sh` files multiple times, one for each env and use env-specific ones in the Cloud Build yaml files. It's bit more concise in implementation where env-specific dirs just need to specified in the `google_cloudbuild_trigger ` resources, and all Cloud Build yamls and `run.sh` can be reused. Users can still run `run.sh` script locally, but just need to supply the target directories to deploy.

One alternative is keeping one `run.sh` and change the argument to `run.sh` from a list of dirs to be just the `env` value. `run.sh` is pre-populated (based on input configs) with if/else statements to switch between envs and choose which list of dirs to deploy. But I'm not sure if that change will bring much benefit but will make the implementation more complicated.

**Comment by umairidris** [comment]
Sounds good, I think we can leave as is for now.
