### ISSUE TITLE
Multi envs don't support multiple folders

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#749]
It is not common for multiple environments to be deployed in the same folder. We should support a way to define different folders for each env.

**Comment by umairidris** [comment]
I see some attempts at supporting this in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/multi_envs.hcl#L218 but the audit and cicd does not run on these folders so I am not sure if it is sufficient. @xingao267 any thoughs?

**Comment by umairidris** [comment]
Ah I see now, it creates the folders within the parent folder. OK, that is fine for now.

**Comment by xingao267** [comment]
Yes. It's already supported. The devops and audit are directly under the root folder. And other projects can be grouped into env-specific folders under the root folder.
