### ISSUE TITLE
Set bool to false in TF Engine config does not actually set it in the final terraform.tfvars

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#77]
Example: `ENABLE_LIEN`

**Comment by umairidris** [comment]
This still doesn't work on foundation recipe.

**Comment by umairidris** [comment]
I tested and it works now for all recipes except devops, which will be fixed by #321. Feel free to reopen after if you still encounter problems around this.
