### ISSUE TITLE
Add ability to pin to provider versions which aren't directly supported

### ISSUE THREAD

**Issue by jordan83** [GoogleCloudPlatform/healthcare-data-protection-suite#771]
Deployments can require raw terraform for resources that aren't directly supported. When custom terraform is needed which uses a provider that isn't used in the deployment there isn't a good way to pin to a provider version for stable deploys.

Currently this can be worked around by adding a version to the provider block but this feature is currently deprecated.

```
provider "kubernetes" {
  token                 = ...
  host                   = ...
  version = "1.13.3" # this is deprecated
}
```

**Comment by xingao267** [comment]
For Kuberetes provider, we should first start pinning it to `~>1.0` in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/components/terraform/main/main.tf#L17

I started to get reports from other solution use cases that they start downloading 2.x kubernetes provider and had issues.

**Comment by xingao267** [comment]
I'll close for now. Pinning kubernetes provider to 1.0 should be sufficient for now.
