### ISSUE TITLE
Add dry-run mode for importer

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/healthcare-data-protection-suite#81]
This mode would just print the commands it would run, instead of actually running them.

**Comment by xingao267** [comment]
Since we are using runner package and interface in V3 as well. This can be done in the same way as V2 https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/runner/runner.go#L78

**Comment by umairidris** [comment]
It would be nice to update the runner package to not add any other text so that you just get a list of commands. That way you can copy the commands you want easily and run them yourself.
