### ISSUE TITLE
Evaluate giving users option to bring their own funcmap.go and plug in to tfengine

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#818]

**Comment by MartinPetkov** [comment]
I think this needs to be clarified a bit. I do not know of a reasonable way to dynamically compile and load Go code after the binary has been built.

If someone wants a custom function, the easiest way is to clone/fork the repo, update the funcmap.go file, and rebase/merge from our repo as needed.

We could also revisit adding [sprig](https://github.com/Masterminds/sprig), which would add more flexibility to templates.

**Comment by xingao267** [comment]
Agreed. If only one or two additional functions needed, that should be upstreamed to our funcmap.go. If multiple ones from sprig can help, we can revisit that.
