### ISSUE TITLE
Add instructions or GCB trigger to clean up resources if integration tests fail

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/healthcare-data-protection-suite#872]
We now have integration tests running in CI/CD, which actually create resources. At the end, they are supposed to destroy those resources to clean up.

The cleanup will probably work most of the time, however if it fails one day, we should have some documentation (or a GCB job we can manually trigger) to clean up manually (and debug in the process).

I imagine the process could be:
1) Generate configs the same way as the integration tests do.
2) Run importer to reconcile state.
3) Run `terraform destroy` again.

Alternatively, we could configure GCB to store the state files as [build artifacts](https://cloud.google.com/build/docs/building/store-build-artifacts) so they're available after-the-fact which would let us skip the import step and know exactly which resources need to be deleted.

**Comment by xingao267** [comment]
Yes. It could fail to destroy resources if something failed or the Cloud Build presubmit job is cancelled during execution. For now, if that happens, we can just simply delete the projects and rerun the integration tests. What CFT does to help with it is having a scheduled job (probably Cloud Scheduler + Cloud Build Trigger) that delete testing projects that are a day old, we can do the same if in the future we have a larger volume of undeleted testing projects.

**Comment by xingao267** [comment]
We don't need to worry about the states which are discarded after each build.

**Comment by MartinPetkov** [comment]
That makes sense. I'll leave this issue open for now if we ever need to work on it, but it's not urgent.

**Comment by xingao267** [comment]
Added to internal doc.
