### ISSUE TITLE
Change how we access Terraform state to not use internal functions

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/healthcare-data-protection-suite#898]
In https://github.com/hashicorp/terraform/commit/c6e36cd835b5c70efff9c7a479640d2e1a3c8222 and as of verstion v0.15.4, Terraform has moved the `states/` package to `internal/`. That means we can no longer use it like we do in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/internal/terraform/state.go, and that we can't upgrade to Terraform-as-a-library v0.15.4.

The only suggestion in the commit is to pin to an older version until we figure out some other way. Probably they expect us to use `terraform show -json` and parse the JSON output.

**Comment by xingao267** [comment]
unassigning myself, will take when i get more time

**Comment by xingao267** [comment]
That's kinda sad.

**Comment by xingao267** [comment]
I'll mark this as obsolete. No plan to do this as the policygen is low priority and we can stay with the old version of the terraform state go library.
