### ISSUE TITLE
Provide schema during generation

### ISSUE THREAD

**Issue by MartinPetkov** [GoogleCloudPlatform/healthcare-data-protection-suite#952]
Currently the schema is not available while generating files from templates, and it results in some duplication, particularly for docs and variables.tf. Making it available would simplify some of the templates.

**Comment by xingao267** [comment]
By generating files, do you mean during tfengine execution or generate_schema_docs?

During tfengine execution, the schema should be available for validation purposes currently.

**Comment by MartinPetkov** [comment]
I mean for use within templates.

**Comment by ernestognw** [comment]
> I mean for use within templates.

To add to the response, yes. It will allow us to only maintain things such as `default`, `validation` and `descriptions` at schema `.hcl` files, so those are inserted into generated files (for example at `variables.tf`) while `generate_schema_docs`
