### ISSUE TITLE
Add devops, groups and cicd recipe to tfengine unit/integration tests

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#974]
so it's tested by a local `terraform plan`. There likely is some historical reason why it's not included at this moment.

**Comment by xingao267** [comment]
Could also look into adding it to the integration test.

**Comment by xingao267** [comment]
Currently the integration test uses `team.hcl`. The cicd template in the `foundation.hcl` used by `team.hcl` is currently using github as the source repo system. That needs to be changed to cloud source repository.

**Comment by thomasfung-hk** [comment]
Added `devops` to `tfengine` integration test and updated build configurations

**Comment by thomasfung-hk** [comment]
Added `groups` to the scope of this ticket since `cicd` is dependent on it.

Currently, `groups` and `cicd` have been added in the fork of the repo.

**Comment by thomasfung-hk** [comment]
Added `groups` and `cicd` to integration test; merged changes.
