### ISSUE TITLE
Remove main.tf templating logic from Devops component

### ISSUE THREAD

**Issue by ernestognw** [GoogleCloudPlatform/healthcare-data-protection-suite#981]
While generating `variables.tf` file transferred some of the major logic into the `terraform.tfvars` file, there were some /conditional resources and fields that are still dependant on templating.

As stated at the discussion of #957, there were 3 main problems with the complete reduction of templating logic:

1. **Conditional resources**: Some resources turned out to be dependant on the existence of some variables. This conditional can be reproduced with the [`count` meta argument](https://www.terraform.io/docs/language/meta-arguments/count.html)
2. **Conditional nested fields**: Conditional nested fields were kept with templated `if` statements due to the restriction that terraform has of omitting nested fields. This can be solved by providing default templated values on `.tfvars` that are the defaults on the underlying terraform modules (every module has a default.). Passing the underlying default is equivalent to not pass anything at all and it avoids the error caused by the nested variable omission.
3. **Descriptions for nested values**: Nested values were not with a description provided, but now, with #953, descriptions are now more maintainable since they're added as variables to the templating, and, now tested against internal resources, I'm proposing a format to show nested descriptions like the following:

```
variable "foo" {
  type = object({
    nestedFoo: object({
      nestedSubFoo: ...,
    }),
    nestedBar: ...
   })

  description = <<EOF
    {{props.foo.description}}

   * nestedFoo = {{...props.nestedFoo.description}}
   ** nestedSubFoo = {{...props.nestedSubFoo.description}}
   * nestedBar = {{...props.nestedFoo.description}}
  EOF
}
```

Applying these 3 principles to devops recipe, templating can be theoretically removed

**Comment by MartinPetkov** [comment]
This seems reasonable to me.
