### ISSUE TITLE
Use GA provider for cloud build triggers

### ISSUE THREAD

**Issue by yeweidaniel** [GoogleCloudPlatform/healthcare-data-protection-suite#998]
Currently tfengine generates the `google_cloudbuild_trigger` resource using the `google-beta` provider. The resource is also [available](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger) in `google` provider so can it use that instead?

**Comment by MartinPetkov** [comment]
Do you run into any issues with using the `google-beta` provider for this resource?

**Comment by yeweidaniel** [comment]
No issues, opening since customers could ask for GA APIs only.
