### ISSUE TITLE
How do you delete deployed resources using the CI/CD pipeline?

### ISSUE THREAD

**Issue by onixalan** [GoogleCloudPlatform/healthcare-data-protection-suite#999]
What is the appropriate method for deleting resources using the CICD pipeline?

**Comment by xingao267** [comment]
If you are deleting resources inside projects, you can remove those configs from tfengine config, regenerate the Terraform configs, then then commit to your version control system, CICD will get triggered and then delete the resources.

If you are deleting projects, it's not yet supported through an IaC way, you can just delete the project using a gcloud command or from the Cloud Console.

**Comment by onixalan** [comment]
Sorry for the delayed response, I was on vacation.

Thanks for the notes on deleting projects.

I am still struggling on how to delete resources within projects with CICD.

> you can remove those configs from tfengine config

1. Do I need to remove the resource blocks/configs from the tfengine config, regenerate the Terraform configs with tfengine in (for example) OUTPUT_PATH=$GIT_ROOT/terraform, then commit to my version control system?
2. Or do I need to remove the resource from `managed_dirs`, regenerate the Terraform configs with tfengine in (for example) OUTPUT_PATH=$GIT_ROOT/terraform, then commit to my version control system?
3. Or do I need to regenerate the Terraform configs in (for example) OUTPUT_PATH=$GIT_ROOT/terraform, remove the Terraform configs belonging to the resource I want to delete in (for example) OUTPUT_PATH=$GIT_ROOT/terraform, then commit to my version control system?

I've tried scenarios 1, 2 and 3 and I'm running into issues. I think I may be misunderstanding what "you can remove those configs from tfengine config". 

I appreciate the help.

**Comment by onixalan** [comment]
My previous [response](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/999#issuecomment-900587574) may be confusing and may be ignored if that helps. I'm looking for more clarification on how to delete resources within projects with CICD. Maybe I'm misunderstanding something from the above answer from @xingao267 . Let me know if additional info is needed from me.

Thanks @xingao267!

**Comment by xingao267** [comment]
Sorry for the delay. The first option you mentioned above is what I meant. What error did you get from doing that?

**Comment by onixalan** [comment]
When I remove/comment the resource/template blocks in my config.hcl file, regenerate the Terraform configs, no changes are made to the Terraform configs in `OUTPUT_PATH=$GIT_ROOT/terraform`. Since no changes are made, I can't commit to my version control. There is no error. This is the part I'm having trouble with.

I've updated my [response](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/999#issuecomment-900587574) above (1.) to clarify I'm unable to commit to my version control.

Thanks

**Comment by xingao267** [comment]
I guess you might have removed an entire `template` block in this case, which basically makes the output folder no longer tracked by `tfengine` binary. In that case, you might be able to use the [-delete_unmanaged_files](https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/cmd/tfengine/main.go#L40) flags to delete those files that are no longer managed by `tfengine`.

cc @MartinPetkov

**Comment by MartinPetkov** [comment]
Xin is probably right. Normally if you remove a block in your config.hcl and you regenerate, it should not generate the parts that you removed. However, if you're reusing the same folder, tfengine will by default not delete "unmanaged" file (files it didn't generate) to avoid deleting your work or any other important files you may have added; for example, you might have created your own .tf files for resources that tfengine doesn't generate, or you might be referencing credentials files, and those shouldn't be deleted unexpectedly.

The flag Xin suggested does delete those, so try it. If it still doesn't work for you, please paste the output of the tfengine command and the relevant parts of the tf plan GCB job and we'll try to help.

**Comment by onixalan** [comment]
Thanks @xingao267 and @MartinPetkov. I figured out how to delete resources with tfengine with your help.

I think the part I misunderstood was the deletion of the configs. I was deleting the entire template, instead of the resource only.

I'm providing an example here so others can use as a reference.

**Before:**

```
template "dev_project_metric_alert" {
  recipe_path = "{{$recipes}}/project.hcl"
  output_path = "./applications/dev_project_metric_alert"
  data = {
    project = {
      project_id = "123-456-789"
      exists     = true
    }
    terraform_addons = {
raw_config = <<EOF
module "metric_alert" {
  source                    = "../modules/metric_alert"
  project_id = module.project.project_id
  email_address             = "gcp-audit-monitoring-alerts@example.org"
  notification_channel_name = "dev notification channel"
} 
EOF
    }
  }
}
```

**After (to trigger deletion):**

# llpr-dev-x9qf3 project metrics alerts
template "dev_project_metric_alert" {
  recipe_path = "{{$recipes}}/project.hcl"
  output_path = "./applications/dev_project_metric_alert"
  data = {
    project = {
      project_id = "123-456-789"
      exists     = true
    }
  }
}
